### ISSUE TITLE
Extend the optimisation methods to BlackBoxOptim

### ISSUE THREAD

**Issue by finmod** [mcreel/Econometrics#2]
An important step forward with Julia in global optimisation is to consider BlackBoxOptim (https://github.com/robertfeldt/BlackBoxOptim.jl). It is very good at sorting out global versus local minima particularly when you have no idea what the starting values should be. See also https://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html

**Comment by mcreel** [comment]
Thanks, I'm aware of BlackBoxOptim, but I have used simulated annealing for the most part for difficult optimization problems, simply because I find that it works well, and due to familiarity. I'd be happy to consider PRs that use BlackBoxOptim in examples, if the contributed examples fit in well with the existing notes.

**Comment by finmod** [comment]
You can find a regression via optimization in the BlackBoxOptim examples https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/regression_via_optimization.jl. It is still a single equation example and deals with OLS, LAD, Lasso and Ridge.

**Comment by mcreel** [comment]
Thanks, those are nice examples. May get around to adding something to the chapter of the notes on optimization using this, but in the mean time, pull requests are welcome.
